#!/bin/sh
#===============
# Script to activate the newest created boot environment
#  For use after an install to BE
#===============
_pool=$1
if [ -z "${_pool}" ] ; then
  echo "No ZFS pool given: cannot determine BE"
  return 1
fi
#see if the pool is already imported
zpool list -H | grep -q "${_pool}"
needimport=$?
# if needimport != 0 then it needs to be imported

#====
# Notes:
# The ISO is not booting from the ZFS pool, so we need to 
#   probe the ZFS pool and figure out the BE list and activate
#   the latest one manually with zfs/zpool commands
#====
#Step 1 : import the pool (do not mount anything from it)
if [ ${needimport} -ne 0 ] ; then
  zpool import -f -N "${_pool}"
fi

#Step 2 : Get the new/current boot environments
_lastBE=`zpool get -H bootfs "${_pool}" | awk '{print $3}'`
_newBE=`zfs list -H -s creation | grep "${_pool}/ROOT/" | awk '{print $1}' | tail -1`

#Step 3 : Set the new BE as the "bootfs" property for the pool
if [ "${_lastBE}" != "${_newBE}" ] ; then
  zpool set "bootfs=${_newBE}" "${_pool}"
  echo "Changed default BE: ${_lastBE} -> ${_newBE}"
fi

#Final step - export the pool again (if we imported it)
if [ ${needimport} -ne 0 ] ; then
  zpool export "${_pool}"
fi
