#!/bin/sh
#=========
# Quick script to find the main EFI partition and install rEFInd
#=========
zipfile="/Trident_refind.zip"

# Find the main EFI partition
efi_part=""
gpart_info=`gpart list`
#while read line
#do
  #echo "line : $line"
#done < "${gpart_info}"

if [ -z "${efi_part}" ] ; then
  echo "[ERROR] Unable to determine EFI partition"
  return 1
fi

# Mount the partition
mnt_dir="/tmp/refind_part"
mkdir ${mnt_dir}
mount_msdosfs "${efi_part}" "${mnt_dir}"
if [ $? -ne 0 ] ; then
  echo "[ERROR] Unable to mount EFI partition: ${efi_part}"
  rmdir "${mnt_dir}"
  return 1
fi
# Extract the refind zipfile into the partition
unzip "${zipfile}" -d "${mnt_dir}"
ret=$?
# unmount the partition
umount "${mnt_dir}"
rmdir "${mnt_dir}"
return $ret
