#!/bin/sh
# Simple script to setup the graphical install environment and 
#  launch the Qt5 installer.

#NOTE: When the ISO boots most of the filesystem is read-only except for /tmp

_conf="/tmp/xorg.conf"
_logfile="/tmp/xorg.log"

setupXorgFonts(){
  #Automatically probe for all the installed fonts
  local _tmp=""
#Now probe for installed fonts and add them to the list
for _fontdir in `ls /usr/local/share/fonts`
do
  _fontdir="/usr/local/share/fonts/${_fontdir}"
  ls "${_fontdir}" | grep -qE ".ttf"
  if [ $? -eq 0 ] ; then
    #Got a good font directory
    if [ -z "${_tmp}" ] ; then
      _tmp="  FontPath     \\\"${_fontdir}\\\""
    else
      _tmp="${_tmp}\\
  FontPath     \\\"${_fontdir}\\\""
    fi
  fi
done
  #Now save this list into the xorg conf
  sed -i '' "s|%%FONTS%%|${_tmp}|g" "${_conf}"
}

#Function: Setup the default xorg.conf file
setupXorgConf(){
  #Inputs: $1 : driver to use
  _driver="$1"

  # Verify that an xorg.conf exists, and generate one as needed
  if [ -e "${_conf}" ] ; then
    rm "${_conf}"
  fi
  #Get the bus ID for the video card
  busid=`pciconf -lv vgapci0 | grep vgapci0 | cut -d : -f 2-4`

  #Now copy over the xorg.conf template and replace the driver/busid in it
  template="/usr/local/share/trident-installer/xorg.conf.template"
  cp -f "${template}" "${_conf}"
  sed -i '' "s|%%BUSID%%|${busid}|g" "${_conf}"
  sed -i '' "s|%%DRIVER%%|${_driver}|g" "${_conf}"
  setupXorgFonts

  # Check for extra kernel modules to load for video driver support
  driver=`cat "${_conf}" | grep "Driver" | cut -d \" -f 2`
  case ${driver} in
	vboxvideo)
		kld_load="vboxguest"
		;;
  esac
  #Now load any modules
  for _kmod in ${kld_load}
  do
	kldload -nq ${_kmod}
  done
}

# Probe the system for UEFI /VBOX and setup the vesa/scfb display driver
_boot=`sysctl -n machdep.bootmethod` #BIOS or UEFI
echo "Detecting system info: ${_boot}"
if [ "${_boot}" = "UEFI" ] ; then
  #UEFI boot : use "scfb" driver
  setupXorgConf "scfb"
else
  #BIOS boot : use "vesa" driver
  setupXorgConf "vesa"
fi
#Make sure the DBUS machine-id file exists (bug in Qt)
# CANNOT RUN ON ISO (read-only filesystem) - hard-coded /etc/machine-id in install files
#dbus-uuidgen --ensure >/dev/null 2>/dev/null

#Start the graphical install
clear
echo "Starting graphical installer in 5 seconds"
echo " - Push [Enter] to drop to a terminal - "
read -t 5 tmp
if [ 0 -eq $? ] ; then
  #Key Pressed - go to terminal
  #Startup a login session if needed
  CLISESSION="/tmp/.runningsession"
  if [ ! -e "${CLISESSION}" ] ; then
    #Now clear the display and print the info message
    clear
    echo "============================"
    echo "To shutdown computer: `shutdown -p now`"
    echo "To restart graphical installer: `start-trident-installer`"
    echo "To run TrueOS command-line installer: `pc-installdialog`"
    echo "============================"
    touch "${CLISESSION}"
    /bin/csh
    rm "${CLISESSION}"
  fi
else
  echo "Launching Trident Installer...."
  xinit /usr/local/bin/trident-installer -- -config ${_conf} -logfile ${_logfile} :0
fi
return 0
