#!/bin/sh
# Simple script to setup the graphical install environment and 
#  launch the Qt5 installer.

#NOTE: When the ISO boots most of the filesystem is read-only except for /tmp

 _conf="/tmp/xorg.conf"
_logfile-"/tmp/xorg.log"

#Function: Setup the default xorg.conf file
setupXorgConf(){
  #Inputs: $1 : driver to use
  _driver="$1"

  # Verify that an xorg.conf exists, and generate one as needed
  if [ ! -e "${_conf}" ] ; then
    #Get the bus ID for the video card
    busid=`pciconf -lv vgapci0 | grep vgapci0 | cut -d : -f 2-4`

    #Now copy over the xorg.conf template and replace the driver/busid in it
    template="/usr/local/share/trident-installer/xorg.conf.template"
    cp -f "${template}" "${_conf}"
    sed -i '' "s|%%BUSID%%|${busid}|g" "${_conf}"
    sed -i '' "s|%%DRIVER%%|${_driver}|g" "${_conf}"
  fi

  # Check for extra kernel modules to load for video driver support
  driver=`cat "${_conf}" | grep "Driver" | cut -d \" -f 2`
  case ${driver} in
	vboxvideo)
		kld_load="vboxguest"
		;;
  esac
  #Now load any modules
  for _kmod in ${kld_load}
  do
	kldload -nq ${_kmod}
  done
}

# Probe the system for UEFI /VBOX and setup the vesa/scfb display driver
_boot=`sysctl -n machdep.bootmethod` #BIOS or UEFI
pciconf -lv | grep -q "VirtualBox Graphics"
if [ $? -ne 0 ] ; then
  #Virtualbox environment
  setupXorgConf "vboxvideo"
elif [ "${_boot}" = "UEFI" ] ; then
  #UEFI boot : use "scfb" driver
  setupXorgConf "scfb"
else
  #BIOS boot : use "vesa" driver
  setupXorgConf "vesa"
fi

#Make sure the DBUS machine-id file exists (bug in Qt)
# CANNOT RUN ON ISO (read-only filesystem) - hard-coded /etc/machine-id in install files
#dbus-uuidgen --ensure >/dev/null 2>/dev/null

#Start the graphical install
xinit /usr/local/bin/trident-installer -- -config ${_conf} -logfile ${_logfile} :0
#shutdown -r now
